app:
  datasource:
    jdbc-url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    pool-size: 20
    driver-class-name=org.postgresql.Driver
  server:
    port: ${PORT:8080}
