spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      jdbc-url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT:8080}
